-- Script generated by SimpleSpy - credits to exx#9394
while wait()do

local args = {
    [1] = "BlowBubble"
}

game:GetService("ReplicatedStorage"):FindFirstChild("4658877511Event"):FireServer(unpack(args))
end